name: edudex_quiz_client
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.10.0
  provider: ^6.0.5
  system_theme: ^2.3.1
  window_manager: ^0.3.0
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.2.0
  url_launcher: ^6.1.7
  clipboard: ^0.1.3
  http: ^1.1.0
  flutter_markdown: ^0.6.13
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  cached_network_image: ^3.2.0
  path_provider: ^2.1.2
  encrypt: ^5.0.3
  process_run: ^0.14.2
  file_picker: ^6.1.1
  file_selector: ^1.0.3
  file_selector_linux: ^0.9.2+1
  file_selector_macos: ^0.9.3+3
  file_selector_windows: ^0.9.3+1
  mutex: ^3.1.0
  network_info_plus: ^4.1.0
  shelf: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/login_illustration.svg
    - assets/logo.png

msix_config:
  capabilities: "runFullTrust,documentsLibrary"

